Initial pass at COMPARISON data
CanDIG/INSPIRE-data-ingest pull request #2
Opened 2020-12-02 15:00 UTC by ljdursi

Add a directory for handling COMPARISON data, and a script for handling that data

2020-12-02 19:54 UTC, Samarth-Agarwal1 requested changes

2020-12-02 19:54 UTC, Samarth-Agarwal1 commented on COMPARISON/data_ingest.py
> +section_to_mapping_types = {
It seems like you're not specifying a `localId` for these mappings. I'm not sure if it is necessary for the Comparison data. Take a look at this section to see if you need it: https://candig-server.readthedocs.io/en/v1.4.0/data.html#clinical-and-pipeline-metadata

2020-12-02 19:54 UTC, Samarth-Agarwal1 commented on COMPARISON/data_ingest.py
> +                new_dict[key] = mapping_dict[key](*args)
It seems like there is only one place where the value of the key is a function and that function doesn't determine on its arguments. So, I think you can just make this `new_dict[key] = mapping_dict[key]()` and you can remove everything else in this else branch.
Then, since `increment_id_num` and `patient_to_id_nums` won't be used anywhere you can remove all instances of them.

2020-12-02 19:59 UTC, ljdursi commented on COMPARISON/data_ingest.py
> +# means that in the medidata rave files, demographics.GENDER_CODE -> Patient.patientId
Whoops!  Quite right

2020-12-02 20:29 UTC, ljdursi commented on COMPARISON/data_ingest.py
> +                new_dict[key] = mapping_dict[key](*args)
Great.  I'll get rid of increment_id_num and patient_to_id_nums, and simplify the logic here...

2020-12-02 20:29 UTC, ljdursi commented on COMPARISON/data_ingest.py
> +section_to_mapping_types = {
Mmm, good point I'll work on this next.

2020-12-03 01:50 UTC, ljdursi commented
I've incorporated your suggestions - now adding localIds to everything except patient and sample, and as long as I was making changes to functions went a little further to allow for transformations on columns.

2020-12-03 17:06 UTC, Samarth-Agarwal1 approved these changes
I think this looks good! If you haven't already, try ingesting it with candig ingest to see if it ingests properly, and if it does this can be merged.

Also, once this is merged, the repo name should be changed since it's not just INSPIRE data ingestion scripts anymore.

2020-12-03 20:22 UTC, ljdursi commented
Great, thanks!

2020-12-03 20:22 UTC, merged

2020-12-03 20:36 UTC, ljdursi commented
Thanks!  I renamed the repo - feel free to change the name if you don't like what I picked